baseURL = "https://example.com"
languageCode = "en"
defaultContentLanguage = "en"
enableRobotsTXT = false
hasCJKLanguage = false
rssLimit = 20
relativeURLs = true
enableEmoji = true
paginate = 5
enableGitInfo = true

title = "Scratchpadium"
theme = "scratchpadium"
copyright = "CC BY-NC-SA 4.0"

[frontmatter]
lastmod = ["lastmod"]

[author]
name = "bbhtt"
email = "bbhtt@bbhtt.in"

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser]
autoHeadingID = true

[params]
style = "auto"
dateFormat = "Jan 2, 2006"
logo = ""
slogan = ""
license = ""
fullRss = false
ipv6ready = false
description = 'Scratchpadium'
title = 'Scratchpadium'

[params.comments]
enable = false

[params.syntax]
use = "none"
theme = "github"
darkTheme = "dracula"

[params.share]
enable = false
addThisId = ""
inlineToolId = ""

[params.nav]
showCategories = false
showTags = false

[[params.nav.custom]]
title = "About"
url = "https://gohugo.io/"
